// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"time"
)

// TimeResponse defines model for TimeResponse.
type TimeResponse struct {
	CurrentTime *time.Time `json:"currentTime,omitempty"`
}

// GetTimeParams defines parameters for GetTime.
type GetTimeParams struct {
	// Timezone The timezone to get the current time for (e.g., 'UTC', 'America/New_York')
	Timezone *string `form:"timezone,omitempty" json:"timezone,omitempty"`
}
