name: Linting
on:
  pull_request:
  push: 
    branches: 
        - frc/ci-lint
    paths: ./git/timeapi

jobs:
  golangci:
    name: Lint golang files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: ./git/timeapi
          version: v1.62

  gomodtidy:
    name: Enforce go.mod tidiness
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Execute go mod tidy and check the outcome
      working-directory: ./git/timeapi
      run: |
        go mod tidy
        exit_code=$(git diff --exit-code)
        exit ${exit_code}

  shelllint:
    name: Lint bash files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Shellcheck
      uses: ludeeus/action-shellcheck@2.0.0
      with:
        scandir: ./git/timeapi
      env:
        # Allow 'source' outside of FILES
        SHELLCHECK_OPTS: -x

  markdownlint:
    name: Lint markdown files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Lint markdown files
      uses: avto-dev/markdown-lint@v1
      with:
        config: './git/timeapi/.markdownlint.yml'
        args: './git/timeapi/**/*.md'
